spring.application.name=app

#Actuator config

# Expose only required endpoints
management.endpoints.web.exposure.include=health,info,metrics,beans

# Show details of health endpoint
management.endpoint.health.show-details=always